[workspace]
resolver = "2"
members = [
    "crates/makima-core",
    "crates/makima-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Biagio Scaglia"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/biagio-scaglia/makima"
homepage = "https://github.com/biagio-scaglia/makima"
readme = "README.md"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.32", features = ["bundled"] }
